import { randomUUID } from "node:crypto";

function row(name, code) {
  return { name, code, active: true };
}

export function seedMasterRows() {
  return {
    products: [
      row("EZY Guard Smart - Z Post", "1G0432NGXX"),
      row("EZY Guard Heavy Duty - Z post", "1G0082NGXX"),
      row("Coil - 4 X 157mm (ID - 510, OD - 1310)", "180179NXXX"),
      row("Other"),
    ],
    customers: [row("Valmont Structures Pty Ltd", "VSPL-AU"), row("Evonith Infra Projects", "EVO-01")],
    suppliers: [
      row("Evonith Value Steel Limited", "EVSL"),
      row("Tata Steel", "TATA"),
      row("JSW Steel", "JSW"),
    ],
    grades: [
      row("HA300", "AS/NZS 1594:2025"),
      row("E350", "IS2062 E350"),
      row("HA250", "AS/NZS 1594:2025"),
      row("Other"),
    ],
    machines: [
      row("Z-post machine", "M-01"),
      row("W-beam machine", "M-02"),
      row("Press line", "M-03"),
      row("Other"),
    ],
    operators: [
      row("Guddu Ray", "OP-101"),
      row("Sarfraz Kazi", "OP-102"),
      row("Sandip Nimbalkar", "OP-103"),
    ],
    documentTypes: [
      row("Mill Test Certificate", "MTC"),
      row("Lab Test Report", "LAB"),
      row("Drawing", "DWG"),
      row("First Piece Inspection Report", "FPI"),
      row("In-process Inspection Report", "IPI"),
      row("Final Inspection Report", "FIR"),
      row("Coating Inspection Report", "CIR"),
      row("Dispatch / Invoice Document", "INV"),
      row("Other", "OTH"),
    ],
  };
}

export function seedTraceRecords() {
  const rows = [
    {
      soNo: "SQ128071",
      lotNo: "1",
      qty: "70",
      product: "EZY Guard Smart - Z Post",
      qadPartNo: "1G0432NGXX",
      asDrawingNo: "10007390",
      drawingRev: "2",
      identification: "ICP VI 02052026 E300 4.3 1650",
      rmThickness: "4.3",
      rmMake: "Evonith Value Steel Limited",
      heatNo: "09469",
      coilNo: "09469SCA",
      millTestReportNo: "10055702",
      labReportNo: "MGTL-0179.1",
      labTestingResult: "Pass",
      applicableStandard: "AS/NZS 1594:2025",
      grade: "HA300",
      coilWeight: "3.3",
      machineNo: "Z-post machine",
      operatorName: "Guddu Ray",
      shift: "First",
      offerQty: "70",
      acceptedQty: "70",
      rejectedQty: "0",
      holdQty: "0",
      rmInspectionReportNo: "001/31.03.2026",
      firstPieceReportNo: "Z-post/26-05/01",
      inprocessReportNo: "Z-post/26-05/02",
      finalReportNo: "Z-post/26-05/03",
      coatingReportNo: "VHSS/2026-01",
      rmInspectionBy: "Sarfraz Kazi",
      finalInspectionBy: "Sandip Nimbalkar",
      conclusion: "Lot Accepted",
      dispatchDate: "2026-05-19",
      dispatchQty: "70",
      invoiceNo: "",
    },
    {
      soNo: "SQ128345",
      lotNo: "2",
      qty: "10",
      product: "EZY Guard Heavy Duty - Z post",
      qadPartNo: "1G0082NGXX",
      asDrawingNo: "10008539",
      drawingRev: "3",
      identification: "ICP VI 26052026 E300 4.3 2000",
      rmThickness: "4.3",
      rmMake: "Evonith Value Steel Limited",
      heatNo: "17397",
      coilNo: "17397TAD",
      millTestReportNo: "10101220",
      labReportNo: "24K-H11302",
      labTestingResult: "Pass",
      applicableStandard: "AS/NZS 1594:2025",
      grade: "HA300",
      coilWeight: "4.1",
      machineNo: "Z-post machine",
      operatorName: "Guddu Ray",
      shift: "First",
      offerQty: "10",
      acceptedQty: "10",
      rejectedQty: "0",
      holdQty: "0",
      rmInspectionReportNo: "002/31.03.2026",
      firstPieceReportNo: "Z-post/26-05/04",
      inprocessReportNo: "Z-post/26-05/05",
      finalReportNo: "Z-post/26-05/06",
      coatingReportNo: "VHSS/2026-1A",
      rmInspectionBy: "Sarfraz Kazi",
      finalInspectionBy: "Sandip Nimbalkar",
      conclusion: "Lot Accepted",
      dispatchDate: "2026-07-03",
      dispatchQty: "10",
      invoiceNo: "HSE26007",
    },
    {
      soNo: "SQ128345",
      lotNo: "3",
      qty: "1",
      product: "Coil - 4 X 157mm (ID - 510, OD - 1310)",
      qadPartNo: "180179NXXX",
      asDrawingNo: "",
      drawingRev: "",
      identification: "",
      rmThickness: "4",
      rmMake: "Tata Steel",
      heatNo: "A183709",
      coilNo: "K408790590",
      millTestReportNo: "907088473",
      labReportNo: "24K-H11944",
      labTestingResult: "Pass",
      applicableStandard: "IS2062 E350",
      grade: "E350",
      coilWeight: "1.4",
      machineNo: "",
      operatorName: "",
      shift: "",
      offerQty: "",
      acceptedQty: "",
      rejectedQty: "",
      holdQty: "",
      conclusion: "Pending",
      finalInspectionBy: "Sandip Nimbalkar",
      dispatchDate: "2026-07-03",
      dispatchQty: "1",
      invoiceNo: "HSE26007",
    },
  ];

  return rows.map((values, i) => ({
    id: `seed-${i + 1}`,
    createdAt: new Date(Date.now() - (rows.length - i) * 864e5).toISOString(),
    values,
    checks: {},
    docs: [],
  }));
}

export { randomUUID };
